# **Task 6: Aggregation and Statistical Functions**
- (Concept: Summarize data with sum, mean, min, max, std, etc.)



- Given this array:
- data= np.array([[10,20,30],[40,50,60],[70,80,90]])


### Q.No 1 Compute the total sum of all elements.


In [2]:
import numpy as np

data = np.array([
                [10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]
                ]
                )
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Q.No 2 Compute the mean of each column.


In [6]:
mean_array = np.mean(data, axis=0)  # if axis= 1 then it caclulate mean by row-wise
mean_array

array([40., 50., 60.])

In [7]:

# Manually
column_1 = np.mean(data[:, 0])
column_2 = np.mean(data[:, 1])
column_3 = np.mean(data[:,2])

column_1, column_2, column_3


(np.float64(40.0), np.float64(50.0), np.float64(60.0))

### Q.No 3 Find the maximum value in the entire array.

In [8]:
max_value = np.max(data)
print(f"Maximum value in the entire array is {max_value}" )

Maximum value in the entire array is 90


### Q.No 4 Compute the standard deviation of each row.

In [11]:
np.std(data, axis=1)  # if axis = 0 then it did column wise

array([8.16496581, 8.16496581, 8.16496581])

### Q.No 5 Find the minimum value in each column.


In [ ]:
np.min(data, axis=0)  # if axis= 1 then it will take smallest value from each row and return as 1-d array

array([10, 20, 30])

### Q.No 6 Compute the median of the flattened array.


### Q.No 7 Calculate the 75th percentile of the entire array using np.percentile.