# **Task 1:** Creating and Initializing Arrays
- Concept: Learn how to make arrays from scratch — the most basic building block

In [2]:
import numpy as np

## Q.No 1: Create a 1D array from the Python list [10, 20, 30, 40, 50].

In [5]:
python_list = [10, 20, 30, 40, 50]
print(f"Pyhton List = { python_list}")

Pyhton List = [10, 20, 30, 40, 50]


In [6]:
array_1d = np.array( python_list)
print(f"Numpy 1-D Array is : { array_1d }")

Numpy 1-D Array is : [10 20 30 40 50]


In [14]:
array_1d.ndim

1

## Q.No 2: Create a 2D array (3 rows × 4 columns) filled with zeros.

In [16]:
array_2d = np.zeros((3,4))
array_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print("Number of Dimensions:", array_2d.ndim) # Number of dimension

# print(f"Number of Dimensions: {array_2d.ndim}:")


Number of Dimensions: 2


# Q.No 3: Create a 3D array of shape (2, 3, 4) filled with ones.

In [ ]:
array_3d = np.ones((2, 3, 4))  # First Blocks, Rows , Columns  , It can also takes dtype=int,float
print("3-D Array of Ones:")
print(array_3d)

3-D Array of Ones:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [24]:
print(f"Number of  Dimensiona : { array_3d.ndim}")

Number of  Dimensiona : 3


## Q.No 4: Create a 1D array containing all integers from 0 to 19 using arange.


In [48]:
#                        start(include) , stop(not included-> excluded) , step(increment in the presvious value to get the next value)
arange_arr_1d = np.arange(start= 0 , stop= 19, step= 2)   # or   np.arange(0,19,2)

print(arange_arr_1d)

[ 0  2  4  6  8 10 12 14 16 18]


## Q.No 5: Create an array of 8 evenly spaced floating-point numbers between 0 and 10 using linspace.

## Q.No 6 Create a 5×5 identity matrix (1s on the diagonal, 0s elsewhere).

## Q.No 7 Create a 4×6 array filled with the constant value 7 using full.