# **Task 7: Reshaping, Transposing, and Flattening**
- (Concept: Change the “shape” of data without changing the values)



### Q.No 1 Create a 1D array of 12 elements and reshape it into a 3×4 matrix.


In [2]:
import numpy as np

In [3]:
array = np.arange(start=0 , stop=12, step= 1)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
reshape_array = array.reshape(3,4)
print(reshape_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Q.No 2 Reshape a 6-element 1D array into a 2×3 matrix, then flatten it back to 1D using flatten().


In [13]:
array = np.random.randint(low=1, high= 7, size=6)
print(array)

[2 5 1 3 3 4]


In [14]:
reshape_array = array.reshape((2,3))
print(reshape_array)

[[2 5 1]
 [3 3 4]]


In [15]:
flattened_array = reshape_array.flatten()
print(flattened_array)

[2 5 1 3 3 4]


### Q.No 3 Transpose a 3×4 random array (swap rows and columns).


In [24]:
random_array = np.random.randint(low=10, high=30, size=(3,4))
print(random_array)

[[17 18 20 19]
 [14 22 26 16]
 [13 13 21 11]]


In [25]:
transpose_array = random_array.transpose()
print(transpose_array)

[[17 14 13]
 [18 22 13]
 [20 26 21]
 [19 16 11]]


### Q.No 4 Reshape a 2×2×3 array into a 3×4 matrix using reshape.


In [29]:
array = np.linspace(start=10, stop= 30, num=12).reshape(2,2,3)
print(array)

[[[10.         11.81818182 13.63636364]
  [15.45454545 17.27272727 19.09090909]]

 [[20.90909091 22.72727273 24.54545455]
  [26.36363636 28.18181818 30.        ]]]


In [30]:
reshape_array = array.reshape(3,4)
print(reshape_array)

[[10.         11.81818182 13.63636364 15.45454545]
 [17.27272727 19.09090909 20.90909091 22.72727273]
 [24.54545455 26.36363636 28.18181818 30.        ]]


### Q.No 5 Create a 4×4 identity matrix and flatten it in row-major order (C order).


In [32]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
flattened_array = identity_matrix.flatten(order="C")  # row wise flatten  .  if "F" then column wise flatten
print(flattened_array)

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


### Q.No 6 Use ravel() on a 5×3 array and confirm it is a view (not a copy) by modifying one value.


### Q.No 7 Stack two 1D arrays vertically using vstack to create a 2×5 matrix.