# **Task 5: Universal Functions (ufuncs)**
- (Concept: Fast mathematical operations applied to every element)

In [2]:
import numpy as np

### Q.No 1 Compute the square root of every element in a 1D array [1, 4, 9, 16, 25].


In [6]:
array_1d = np.array([1, 4, 9, 16, 25])

In [7]:
sqrt_arr_1d = np.sqrt(array_1d)

In [8]:
print(f"1-D array {array_1d} and it's square root is {sqrt_arr_1d}")

1-D array [ 1  4  9 16 25] and it's square root is [1. 2. 3. 4. 5.]


### Q.No 2 Compute the sine of every element in np.linspace(0, np.pi, 5).


In [33]:
array = np.linspace(start=0, stop=np.pi, num=5)   # np.linspace(0, np.pi, 5) # start and stop both are included
array

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [34]:
sine_array = np.sin(array)
sine_array

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

### Q.No 3 Calculate the exponential (exp) of a 2×3 array of random numbers between 0 and 2.


In [ ]:
nor_array = np.random.uniform(low=0, high=2, size=(2,3))     # (0, 2, size=(2,3)) or  (0, 2, (2,3))  start 0 is include but end 2 is excluded
nor_array

array([[0.66848211, 0.12361008, 1.71048147],
       [1.71676139, 1.10987936, 0.30327737]])

In [32]:
exp_array = np.exp(nor_array)

exp_array

array([[1.95127324, 1.13157456, 5.53162416],
       [5.56647162, 3.03399236, 1.35429005]])

### Q.No 4 Compute the natural logarithm (log) of [1, 10, 100, 1000].

In [35]:
array = np.array([1, 10, 100, 1000])
array

array([   1,   10,  100, 1000])

In [39]:
nlog_array = np.log(array)  # natural log base e(2.17) , common log10 and binary log have base 2 i.e log2


In [40]:
print(f"Arary :\n {array}")
print(f"Natural log array : \n {nlog_array}")

Arary :
 [   1   10  100 1000]
Natural log array : 
 [0.         2.30258509 4.60517019 6.90775528]


### Q.No 5 Find the absolute value of [-5, 3, -8, 2, -1].

In [41]:
array = np.array([-5,3,-8,2,-1])
array

array([-5,  3, -8,  2, -1])

In [42]:
absolute_array = np.abs( array )

In [43]:
print(f"Array : {array} and it's absolute is : {absolute_array}")

Array : [-5  3 -8  2 -1] and it's absolute is : [5 3 8 2 1]


### Q.No 6 Use np.maximum to get the element-wise maximum between two arrays a = [1,5,3] and b = [4,2,6].


### Q.No 7 Round every element of a random float array (between 0 and 10) to 2 decimal places using np.round.