# Task 4: Arithmetic Operations and Broadcasting
- (Concept: Perform math on entire arrays without loop)


### Q.No 1 Create two 1D arrays a = [1,2,3,4] and b = [10,20,30,40] and add them element-wise.



In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [5]:
a + b

array([11, 22, 33, 44])

### Q.No 2 Multiply a 3×3 matrix of ones by the scalar 5.


In [10]:
ones_matrix = np.ones(shape=(3,3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones_matrix_5 = ones_matrix * 5
ones_matrix_5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

### Q.No 3 Create a 1D array [1, 2, 3] and add it to a 3×3 matrix of zeros using broadcasting.


In [15]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [16]:
zeros_matrix = np.zeros(shape=(3,3))
zeros_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
result = zeros_matrix + array_1d  # result is broadcasted matrix i.e [[1,2,4],[1,2,3],[1,2,3]] and then added to 3x3 zeros
result

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### Q.No 4 Subtract 10 from every element of a 4×4 random integer array (0–20).


In [43]:
random_array = np.random.randint(0, 20, (4,4))
random_array

array([[12, 15, 15, 13],
       [ 0,  1,  3, 15],
       [14,  6,  6, 15],
       [ 8,  9,  2, 12]], dtype=int32)

In [44]:
result = random_array - 10
result

array([[  2,   5,   5,   3],
       [-10,  -9,  -7,   5],
       [  4,  -4,  -4,   5],
       [ -2,  -1,  -8,   2]], dtype=int32)

### Q.No 5 Divide a 2×5 array of random floats by 2 (element-wise).


In [60]:
random_arr_float = np.random.random((2,5))
random_arr_float


array([[0.65898516, 0.78829889, 0.25499444, 0.67658748, 0.89770727],
       [0.72703537, 0.96595589, 0.10476908, 0.60083203, 0.47329839]])

In [62]:
result = random_arr_float/2
result

array([[0.32949258, 0.39414944, 0.12749722, 0.33829374, 0.44885364],
       [0.36351769, 0.48297794, 0.05238454, 0.30041602, 0.23664919]])

### Q.No 6 Create a column vector of shape (5,1) and a row vector of shape (1,5) and multiply them (outer product via broadcasting).


### Q.No 7 Compute element-wise power: raise each element of [2, 3, 4, 5] to the power of [3, 2, 1, 0].