
# Task 3: Indexing and Slicing
- (Concept: Access specific elements or sub-arrays)

### Q.No 1 Create a 1D array [10, 20, 30, 40, 50, 60, 70] and extract the element at index 4.


In [1]:
import numpy as np

In [2]:
array_1d = np.array([10,20,30,40,50,60, 70])

In [4]:
print(f"Value at index 4 is {array_1d[4]}")

Value at index 4 is 50


### Q.No 2 Using the same array, slice and get elements from index 2 to 5 (inclusive of 2, exclusive of 6).


In [5]:
array_1d[2 : 6]  #  inluded : excluded

array([30, 40, 50, 60])

### Q.No 3 Create a 3×4 array of random integers (0–9) and extract the entire second row.

In [47]:
random_array = np.random.randint(9, size=(3,4))
random_array

array([[6, 1, 8, 0],
       [7, 3, 5, 4],
       [4, 4, 3, 8]], dtype=int32)

In [48]:
print(f"Second row of random_array is {random_array[1]}")

Second row of random_array is [7 3 5 4]


### Q.No 4 From the same 3×4 array, extract the sub-matrix consisting of the first two rows and last two columns.

In [49]:
random_array[0:2 , 2:4]   # after : not included

array([[8, 0],
       [5, 4]], dtype=int32)

In [51]:
random_array[ : 2, 2: ]

array([[8, 0],
       [5, 4]], dtype=int32)

### Q.No 5 Use negative indexing to get the last two elements of a 1D array [5, 10, 15, 20, 25, 30].

In [52]:
array_1d = np.array([5,10,15,20,25,30])
array_1d

array([ 5, 10, 15, 20, 25, 30])

In [53]:
array_1d[-2:]

array([25, 30])

### Q.No 6 Create a 5×5 array of zeros and set the center 3×3 block to 1 using slicing.

### Q.No 7 From a 4×4 identity matrix, extract only the diagonal elements as a 1D array.